---
theme: jekyll-theme-cayman
title: Welcome to the Phanalytix Project Page!
description:  Phanalytix is a project based on the creation of an original dataset through the use of three APIs, phish.in, phish.net, and Google's Maps API, along with web-scraping from phish.in and phish.net.  The dataset is a compilation of the shows and songs data of the band Phish. There is also a Shiny App with two components that can be used by Phish fans and explorers.
---
